version: 2.1

master-only: &master-only
  filters:
    branches:
      only: master

executors:
  builder:
    docker:
      - image: duckpodger/python3-node-aws-terraform

jobs:
  setup:
    executor: builder
    steps:
      - restore_cache:
          keys:
            - git-v3-{{ .Branch }}-
            - git-v3-

      - checkout

      - run:
          name: update git submodule
          command: |
            git submodule init
            git submodule update --remote
            git submodule sync

      - restore_cache:
          keys:
            - other-v1-{{ .Branch }}-
            - other-v1-

      - run:
          name: install virtual env
          command: |
            export PIPENV_VENV_IN_PROJECT=true
            pipenv install --dev --deploy
            pipenv clean
            if [ ! -d "test-reports" ]; then
              mkdir test-reports
            fi

      - run:
          name: terraform
          command: |
            . .circleci/env.sh
            cd infrastructure
            terraform init -reconfigure -backend-config "bucket=$APP_NAME-terraform-state"
            terraform get --update
            terraform workspace new $SSM_SOURCE_STAGE || terraform workspace select $SSM_SOURCE_STAGE
            echo checking formatting
            terraform fmt -check=true
            echo making the plan
            terraform plan -var ssm_source_stage=$SSM_SOURCE_STAGE -var account_id=$ACCOUNT_ID -var app_name=$APP_NAME -var route53_role=$ROUTE53_ROLE -no-color -out=plan.file > terraform.plan

      - persist_to_workspace:
          root: .
          paths:
            - "*"

      - store_artifacts:
          path: .generated

      - store_artifacts:
          path: infrastructure/plan.file

      - store_artifacts:
          path: infrastructure/terraform.plan

      - store_artifacts:
          path: .generated/*

      - save_cache:
          key: git-v3-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - save_cache:
          key: other-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "infrastructure/.terraform"
            - ".venv"
            - ".generated"
            - ".pytest_cache"

  unit-test:
    executor: builder
    steps:
      - attach_workspace:
          at: .
      - run:
          name: unit tests
          command: |
            . .circleci/env.sh
            pytest --junitxml=test-reports/junit.xml -s -vv -m unit tests
      - store_test_results:
          path: test-reports

  deploy:
    executor: builder
    steps:
      - attach_workspace:
          at: .
      # TODO change this when we move on to having multiple environments
      - run:
          name: deploy
          command: |
            . .circleci/env.sh
            cd infrastructure
            terraform workspace new dev || terraform workspace select dev
            terraform apply plan.file

  deploy-moj:
    executor: builder
    steps:
      - restore_cache:
          keys:
            - git-v3-{{ .Branch }}-
            - git-v3-

      - checkout

      - restore_cache:
          keys:
            - tf-moj-v1-{{ .Branch }}-
            - tf-moj-v1-

      - run:
          name: update git submodule
          command: |
            git submodule init
            git submodule update --remote
            git submodule sync

      - run:
          name: install virtual env
          command: |
            export PIPENV_VENV_IN_PROJECT=true
            pipenv install --dev --deploy
            if [ ! -d "test-reports" ]; then
              mkdir test-reports
            fi

      - run:
          name: terraform apply
          command: |
            unset AWS_PROFILE
            export AWS_ACCESS_KEY_ID=$MOJ_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$MOJ_SECRET_ACCESS_KEY
            set -x
            . .circleci/env.sh
            cd infrastructure
            terraform init -backend-config "bucket=$MOJ_APP_NAME-terraform-state" -reconfigure
            terraform workspace new dev || terraform workspace select dev
            terraform apply -auto-approve -var account_id=$MOJ_ACCOUNT_ID -var app_name=$MOJ_APP_NAME -var route53_role=$ROUTE53_ROLE 

      - save_cache:
          key: git-v3-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"

      - save_cache:
          key: tf-moj-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "infrastructure/.terraform"
            - ".venv"
            - ".generated"
            - ".pytest_cache"

workflows:
  version: 2
  terraform-infrastructure:
    jobs:
      - setup
      - unit-test:
          requires: [ setup ]
      - approve:
          type: approval
          requires: [ unit-test ]
          <<: *master-only
      - deploy:
          requires: [ approve ]
          <<: *master-only
      - deploy-moj:
          requires: [ approve ]
          <<: *master-only
